config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, :cocktail, :ingredient, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :rating, :detail, presence: true
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(ct_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def ct_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
    @review.cocktail = @cocktail
  end

  def create
    cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = cocktail
    if @review.save
      redirect_to cocktail_path(cocktail)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:detail, :rating, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<h1 class="text-center mt-2">List of All Cocktails</h1>

<div class="row">
  <%  @cocktails.each do |cocktail|%>
    <div class="col-sm-6 col-md-4 d-flex justify-content-center">
      <div class="card my-2 bg-light text-dark" style="width: 20rem;">
        <%= cl_image_tag cocktail.photo.key, height: 300, crop: :fill, class: "card-img-top" %>
        <div class="card-body">
        <h5 class="card-title"><%= cocktail.name %></h5>
        </div>
        <div class="card-footer">
        <%= link_to "More info on #{cocktail.name}", cocktail_path(cocktail) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h1>Name your Cocktail</h1>

<%= simple_form_for @cocktail, defaults: { input_html: { class: 'col-sm-6' } } do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, 'Submit new Cocktail', class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back to all Cocktails", cocktails_path, class: 'btn btn-primary my-2' %>

app/views/cocktails/show.html.erb
<div class="cocktail-page">
  <h1><%= @cocktail.name %></h1>

  <%= cl_image_tag @cocktail.photo.key, height: 300, crop: :fill %>

  <h3 class="my-2">Reviews</h3>
  <ul>
    <%  @cocktail.reviews.each do |review|%>
      <li>(<%= review.rating %> out of 5) <p><%= review.detail %>
        <%= link_to " ", review_path(review), method: :delete, class: "fas fa-trash" %></li>
    <% end %>
  </ul>

  <%= link_to "Add a review", new_cocktail_review_path(@cocktail), class: 'btn btn-primary my-2' %>

  <h3 class="my-2">Doses</h3>
  <ul>
    <%  @cocktail.doses.each do |dose|%>
      <li><%= dose.description %> <%= dose.ingredient.name %> <%= link_to " ", dose_path(dose), method: :delete, class: "fas fa-trash" %></li>
    <% end %>
  </ul>


  <h3 class="my-2">Add a New Dose</h3>

  <%= simple_form_for [@cocktail, @dose], defaults: { input_html: { class: 'col-sm-6' } } do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, collection: Ingredient.order(:name) %>
    <%= f.button :submit, 'Submit new Dose', class: 'btn btn-primary' %>
  <% end %>

  <%= link_to "Back to all Cocktails", cocktails_path, class: 'btn btn-primary my-2' %>
</div>

app/views/doses/new.html.erb
<h1>Doses#new</h1>

<%= simple_form_for [@cocktail, @dose], defaults: { input_html: { class: 'col-sm-6' } } do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, collection: Ingredient.order(:name) %>
  <%= f.button :submit, 'Submit new Dose', class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back to #{@cocktail.name} page", cocktail_path(@cocktail), class: 'btn btn-primary my-2' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktails Galore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>

<%= simple_form_for [@cocktail, @review], defaults: { input_html: { class: 'col-sm-6' } } do |f| %>
  <%= f.input :detail %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.button :submit, 'Submit new Review', class: 'btn btn-primary' %>
<% end %>

<%= link_to "Back to #{@cocktail.name} page", cocktail_path(@cocktail), class: 'btn btn-primary my-2' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light">
  <div class="container-fluid">
    <%= link_to "Cocktails Galore", root_path, class: "navbar-brand" %>
    <span class="navbar-nav">
      <%= button_to "Create Cocktail", new_cocktail_path, method: :get, class: "btn btn-outline-primary" %>
    </span>
  </div>
</nav>